# Generated by Django 3.0.7 on 2020-06-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitt',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
